function P = codigo_mtzP(t,Kt_d,Kt_w,R_d,R_w,n_d,n_w)
%codigo_mtzP
%    P = codigo_mtzP(T,Kt_d,Kt_w,R_d,R_w,N_D,N_W)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    11-Aug-2023 19:43:34

t2 = 1.0./R_d;
t3 = 1.0./R_w;
t4 = Kt_d.*n_d.*t2.*1.2e+1;
t5 = Kt_w.*n_w.*t3.*1.2e+1;
P = reshape([t4,-t4,0.0,0.0,0.0,0.0,t5,-t5],[4,2]);
end
