function O = codigo_mtzO(t,L,Mb,Mr,Mw,Rw,d,g,phi_,psi_)
%codigo_mtzO
%    O = codigo_mtzO(T,L,Mb,Mr,Mw,Rw,D,G,PHI_,PSI_)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    11-Aug-2023 19:43:19

t2 = cos(psi_);
O = [0.0;-g.*sin(phi_).*(Mb.*Rw+Mr.*Rw+Mw.*Rw+L.*Mb.*t2+L.*Mr.*t2+Mr.*d.*t2);0.0;-g.*cos(phi_).*sin(psi_).*(Mr.*d+L.*Mb+L.*Mr)];
end
