function out1 = function_G(phi_,psi_)
%function_G
%    OUT1 = function_G(PHI_,PSI_)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    29-Aug-2023 12:49:16

out1 = [0.0;sin(phi_).*(cos(psi_).*4.079517952e-1+1.45905e-1).*(-9.81e+2./1.0e+2);0.0;cos(phi_).*sin(psi_).*(-4.002007110912)];
end
