function out1 = function_G(phi_,psi_)
%function_G
%    OUT1 = function_G(PHI_,PSI_)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    28-Nov-2023 18:55:45

out1 = [0.0;sin(phi_).*(cos(psi_).*4.079517952e-1+1.45905e-1).*(-4.9e+1./5.0);0.0;cos(phi_).*sin(psi_).*(-3.99792759296)];
end
