function out1 = function_G(phi_,psi_)
%function_G
%    OUT1 = function_G(PHI_,PSI_)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    27-Feb-2024 20:51:11

out1 = [0.0;sin(phi_).*(cos(psi_).*4.079517952e-1+1.525932e-1).*(-9.81e+2./1.0e+2);0.0;cos(phi_).*sin(psi_).*(-4.002007110912)];
end
