function out1 = function_M(psi_)
%function_M
%    OUT1 = function_M(PSI_)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    02-Apr-2024 15:12:03

t2 = cos(psi_);
t3 = t2.*2.89645774592e-2;
mt1 = [1.40362437e-2,1.40362437e-2,0.0,0.0,1.40362437e-2];
mt2 = [t2.*5.79291549184e-2+t2.^2.*1.01989758972032e-1+1.017603609e-1,0.0,0.0,0.0,0.0,1.14160855e-2,t3,0.0,0.0,t3,1.43889758972032e-1];
out1 = reshape([mt1,mt2],4,4);
end
