function out1 = function_P
%function_P
%    OUT1 = function_P

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    11-Dec-2023 15:08:00

out1 = reshape([6.766378966696805,-6.766378966696805,0.0,0.0,0.0,0.0,1.7653879583325,-1.7653879583325],[4,2]);
end
