function M = codigo_mtzM(t,Jbr,Jbw,Jr,Jw,L,Mb,Mr,Mw,Rw,d,psi_)
%codigo_mtzM
%    M = codigo_mtzM(T,Jbr,Jbw,Jr,Jw,L,Mb,Mr,Mw,Rw,D,PSI_)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    10-Aug-2023 10:16:51

t2 = cos(psi_);
t3 = Mr.*d;
t4 = L.^2;
t5 = Rw.^2;
t7 = L.*Mb;
t8 = L.*Mr;
t9 = t2.^2;
t10 = Mb.*t5;
t11 = Mr.*t5;
t12 = Mw.*t5;
t13 = t3+t7+t8;
t14 = Rw.*t2.*t13;
M = reshape([Jr,Jr,0.0,0.0,Jr,Jbw+Jr+t10+t11+t12+L.*t3.*t9.*2.0+Mb.*t4.*t9+Mr.*t4.*t9+Rw.*t2.*t3.*2.0+Rw.*t2.*t7.*2.0+Rw.*t2.*t8.*2.0+d.*t3.*t9,0.0,0.0,0.0,0.0,Jw+t10+t11+t12,t14,0.0,0.0,t14,Jbr+L.*t3.*2.0+Mb.*t4+Mr.*t4+d.*t3],[4,4]);
end
